mosque_list = {'mosques': [{'id': 1, 'name': 'The Forum Value Mall Masjid', 'locality': 'Whitefield'},
                           {'id': 2, 'name': 'Jamia Masjid White Field', 'locality': 'Whitefield'},
                           {'id': 3, 'name': 'Masjid-E-Noor', 'locality': 'Whitefield'},
                           {'id': 4, 'name': 'Masjid', 'locality': 'Whitefield'},
                           {'id': 5, 'name': 'Jama Masjid Whitefield', 'locality': 'Whitefield'}]}

mosque_detail = [{'id': 1,
                  'name': 'The Forum Value Mall Masjid',
                  'address': {
                      'addressline1': 'No. 62, Fourm Value Mall Rd, Palm Meadows',
                      'addressline2': 'Whitefield Main Rd, Prestige Ozone',
                      'locality': 'Whitefield',
                      'city': 'Bengaluru',
                      'district': 'Karnataka',
                      'pincode': '560066'
                  },
                  'phone': '9765454321',
                  'time': {'FAZR': '05:45',
                           'ZOHR': '13:30',
                           'ASR': '17:00',
                           'MAGHRIB': '18:30',
                           'ISHA': '20:30'}},
                 {'id': 2,
                  'name': 'Jamia Masjid White Field',
                  'address': {
                      'addressline1': 'Whitefield Main Rd, Dodsworth Layout',
                      'addressline2': '',
                      'locality': 'Whitefield',
                      'city': 'Bengaluru',
                      'district': 'Karnataka',
                      'pincode': '560066'
                  },
                  'phone': '9765454321',
                  'time': {'FAZR': '05:45',
                           'ZOHR': '13:30',
                           'ASR': '17:00',
                           'MAGHRIB': '18:30',
                           'ISHA': '20:30'}},
                 {'id': 3,
                  'name': 'Masjid-E-Noor',
                  'address': {
                      'addressline1': 'Gandhipuram, 5th Cross Road',
                      'addressline2': 'Immadihalli Rd, Gandhipuram',
                      'locality': 'Whitefield',
                      'city': 'Bengaluru',
                      'district': 'Karnataka',
                      'pincode': '560066'
                  },
                  'phone': '9765454321',
                  'time': {'FAZR': '05:45',
                           'ZOHR': '13:30',
                           'ASR': '17:00',
                           'MAGHRIB': '18:30',
                           'ISHA': '20:30'}},
                 {'id': 4,
                  'name': 'Masjid ITPL',
                  'address': {
                      'addressline1': 'Masjid Rd, Shivaji Nagar',
                      'addressline2': 'Basavanna Nagar',
                      'locality': 'Whitefield',
                      'city': 'Bengaluru',
                      'district': 'Karnataka',
                      'pincode': '560066'
                  },
                  'phone': '9765454321',
                  'time': {'FAZR': '05:45',
                           'ZOHR': '13:30',
                           'ASR': '17:00',
                           'MAGHRIB': '18:30',
                           'ISHA': '20:30'}},
                 {'id': 5,
                  'name': 'Sunni Masjid',
                  'address': {
                      'addressline1': 'Deens Academy Campus, ECC Rd',
                      'addressline2': 'Prithvi Layout',
                      'locality': 'Whitefield',
                      'city': 'Bengaluru',
                      'district': 'Karnataka',
                      'pincode': '560066'
                  },
                  'phone': '',
                  'time': {'FAZR': '05:45',
                           'ZOHR': '13:30',
                           'ASR': '17:00',
                           'MAGHRIB': '18:30',
                           'ISHA': '20:30'}}]
