"""empty message

Revision ID: 4f65c2238756
Revises: c251a5f58acc
Create Date: 2019-04-27 17:36:10.053779

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '4f65c2238756'
down_revision = 'c251a5f58acc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE timings RENAME COLUMN time_asr TO asr')
    op.execute('ALTER TABLE timings RENAME COLUMN time_zohr TO dhuhr')
    op.execute('ALTER TABLE timings RENAME COLUMN time_fazr TO fajr')
    op.execute('ALTER TABLE timings RENAME COLUMN time_isha TO isha')
    op.execute('ALTER TABLE timings RENAME COLUMN time_maghrib TO maghrib')
    # ### end Alembic commands ##


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE timings RENAME COLUMN asr TO time_asr')
    op.execute('ALTER TABLE timings RENAME COLUMN dhuhr TO time_zohr')
    op.execute('ALTER TABLE timings RENAME COLUMN fajr TO time_fazr')
    op.execute('ALTER TABLE timings RENAME COLUMN isha TO time_isha')
    op.execute('ALTER TABLE timings RENAME COLUMN maghrib TO time_maghrib')
    # ### end Alembic commands ###
