"""empty message

Revision ID: c251a5f58acc
Revises: 
Create Date: 2019-04-16 00:45:54.101985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c251a5f58acc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timings',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('time_fazr', sa.DateTime(), nullable=True),
    sa.Column('time_zohr', sa.DateTime(), nullable=True),
    sa.Column('time_asr', sa.DateTime(), nullable=True),
    sa.Column('time_maghrib', sa.DateTime(), nullable=True),
    sa.Column('time_isha', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timings')
    # ### end Alembic commands ###
